VER=1.0

PREFIX=./releases/1.0
BIN_PREFIX=$(PREFIX)/bin
RELEASE_PREFIX=$(PREFIX)/peasy

ERL=erl
ERL_FLAGS=+Ktrue +A 128
ERL_TOP=/opt/local/lib/erlang

DIALYZER=dialyzer
DIALYZER_OPTS=-Wunmatched_returns -Woverspecs -Wunderspecs
DIALYZER_BUILD_PATHS= \
	$(ERL_TOP)/lib/kernel-2.13.2/ebin \
	$(ERL_TOP)/lib/stdlib-1.16.2/ebin \
	$(ERL_TOP)/lib/mnesia-4.4.10/ebin \
	$(ERL_TOP)/lib/erts-5.7.2/ebin 